## Q-2. 

Imagine you have a dataset where you have different features like Age ,Gender , Height , Weight , BMI , and Blood Pressure 
and you have to classify the people into
different classes like Normal , Overweight , Obesity , Underweight , and Extreme Obesity by using
any 4 different classification algorithms. 

Now you have to build a model which
can classify people into different classes.

Dataset link: https://www.kaggle.com/datasets/ankurbajaj9/obesity-levels?resource=download

In [39]:
# Required Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

### Data Ingestion

In [3]:
file_path = "ObesityDataSet_raw_and_data_sinthetic.csv"
df = pd.read_csv(file_path)

In [4]:
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

### EDA & FE

#### Basic Analysis

In [8]:
df

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [6]:
# Shape of the dataset
print(f"No of Rows -> {df.shape[0]} \nNo of columns -> {df.shape[1]}")

No of Rows -> 2111
No of columns -> 17

In [7]:
# General Information about the feattures
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          2111 non-null   object
 1   Age                             2111 non-null   float64
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   family_history_with_overweight  2111 non-null   object
 5   FAVC                            2111 non-null   object
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   CAEC                            2111 non-null   object
 9   SMOKE                           2111 non-null   object
 10  CH2O                            2111 non-null   float64
 11  SCC                             2111 non-null   object
 12  FAF                             2111 non-null   float64
 13  TUE                             2111 non-null   float64
 14  CALC                            2111 non-null   object
 15  MTRANS                          2111 non-null   object
 16  NObeyesdad                      2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

**Comments:**

1. No missing/null values found in the data.
2. 8 features having numeric data and remaining 8 contain text data.
3. "NObeyesdad" is our target feature.

In [10]:
df.columns

Index(['Gender', 'Age', 'Height', 'Weight', 'family_history_with_overweight',
       'FAVC', 'FCVC', 'NCP', 'CAEC', 'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE',
       'CALC', 'MTRANS', 'NObeyesdad'],
      dtype='object')

**Feature Details**

**Gender**: Represents the gender of the individual (Male or Female).

**Age**: Refers to the age of the individual in years.

**Height**: Indicates the height of the individual in centimeters.

**Weight**: Represents the weight of the individual in kilograms.

**family_history_with_overweight**: Indicates whether the individual has a family history of overweight or obesity (Yes or No).

**FAVC**: Represents the consumption of high-caloric food frequency (Frequent or Not frequent).

**FCVC**: Represents the consumption of vegetables frequency (Frequent or Not frequent).

**NCP**: Refers to the number of main meals per day (1, 2, 3, or more).

**CAEC**: Represents the consumption of food between meals frequency (Frequently, Sometimes, or No).

**SMOKE**: Indicates whether the individual is a smoker or not (Yes or No).

**CH2O**: Refers to the daily water intake (in liters).

**SCC**: Represents the calories consumption monitoring (Yes or No).

**FAF**: Refers to the physical activity frequency (0 - very low, 1 - low, 2 - medium, 3 - high, 4 - very high).

**TUE**: Represents the daily time spent on TV or computer use (0 - none, 1 - 1 hour, 2 - 2 hours, 3 - 3 hours, 4 - more than 4 hours).

**CALC**: Indicates whether the individual is using a calculator at work or school (Always, Sometimes, or No).

**MTRANS**: Represents the transportation method used (Automobile, Bike, Motorbike, Public Transportation, or Walking).

**NObeyesdad**: Represents the class label indicating the level of obesity (Target variable). It includes different levels such as:

- Insufficient Weight
- Normal Weight
- Overweight Level I
- Overweight Level II
- Obesity Type I
- Obesity Type II
- Obesity Type III (Extreme Obesity)

#### Feature 1: 

**Gender**: Represents the gender of the individual (Male or Female).

- Gender is a Categorical variable without any inherent order or we can say it is Nominal Variable.
- We can't use Label Encoding to convert Gender to Numerical Variable.
- We can use One Hot Encoding to convert Gender to Numerical Variable.

In [17]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [18]:
df['Gender'].dtype

dtype('O')

In [31]:
# Initialize OneHotEncoder
ohe = OneHotEncoder()

# Fit-transform the categorical column
gender_encoded = ohe.fit_transform(df[['Gender']]).toarray()

df_gender = pd.DataFrame(gender_encoded, columns=ohe.get_feature_names_out(['Gender']))

df_gender

      Gender_Female  Gender_Male
0               1.0          0.0
1               1.0          0.0
2               0.0          1.0
3               0.0          1.0
4               0.0          1.0
...             ...          ...
2106            1.0          0.0
2107            1.0          0.0
2108            1.0          0.0
2109            1.0          0.0
2110            1.0          0.0

[2111 rows x 2 columns]

In [32]:
# Concatenate the original DataFrame with the encoded columns
df = pd.concat([df, df_gender], axis=1)

In [35]:
# Dropping 'Gender' column
df.drop(columns=['Gender'], axis=1, inplace=True)

In [36]:
# Updated dataframe
df.head()

,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad,Gender_Female,Gender_Male
0,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,1.0,0.0
1,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,1.0,0.0
2,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,0.0,1.0
3,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,0.0,1.0
4,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,0.0,1.0

#### Feature 5:

**family_history_with_overweight**: Indicates whether the individual has a family history of overweight or obesity (Yes or No).

- this categorical variable contains Ordinal values
- this can be converted to a numeric variable by using LabelEncoding

In [37]:
df['family_history_with_overweight'].unique()

array(['yes', 'no'], dtype=object)

In [38]:
df['family_history_with_overweight'].dtype

dtype('O')

In [40]:
# Creating a instance of label Encoder.
le = LabelEncoder()
 
# Using .fit_transform function to fit label
# encoder and return encoded label
label = le.fit_transform(df['family_history_with_overweight'])
 
# printing label
label

array([1, 1, 1, ..., 1, 1, 1])

In [41]:
# Encoding the 'family_history_with_overweight' column
df['family_history_with_overweight'] = label

# Updated Dataframe 
df.head()

,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad,Gender_Female,Gender_Male
0,21.0,1.62,64.0,1,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,1.0,0.0
1,21.0,1.52,56.0,1,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,1.0,0.0
2,23.0,1.80,77.0,1,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,0.0,1.0
3,27.0,1.80,87.0,0,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,0.0,1.0
4,22.0,1.78,89.8,0,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,0.0,1.0

#### Features 6:

**FAVC**: Represents the consumption of high-caloric food frequency (Frequent or Not frequent).

- this feature contain binary values - yes or no.
- this can also be encoded using LabelEncoder function

In [42]:
df['FAVC'].unique()

array(['no', 'yes'], dtype=object)

In [43]:
df['FAVC'].dtype

dtype('O')

In [44]:
# Creating a instance of label Encoder.
le = LabelEncoder()
 
# Using .fit_transform function to fit label
# encoder and return encoded label
favc_encoded = le.fit_transform(df['FAVC'])
 
# printing label
favc_encoded

array([0, 0, 0, ..., 1, 1, 1])

In [45]:
# Encoding the 'family_history_with_overweight' column
df['FAVC'] = favc_encoded

# Updated Dataframe 
df.head()

,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad,Gender_Female,Gender_Male
0,21.0,1.62,64.0,1,0,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,1.0,0.0
1,21.0,1.52,56.0,1,0,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,1.0,0.0
2,23.0,1.80,77.0,1,0,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,0.0,1.0
3,27.0,1.80,87.0,0,0,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,0.0,1.0
4,22.0,1.78,89.8,0,0,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,0.0,1.0

#### Feature 9:

**CAEC**: Represents the consumption of food between meals frequency ('Sometimes', 'Frequently', 'Always', 'no').

- this categorical variable contain 4 values - 'Sometimes', 'Frequently', 'Always', 'no'
- we can consider this as ordinal variable with the following orders
    - 'no' = 0
    - 'Sometimes' = 1
    - 'Frequently' = 2
    - 'Always' = 3
- this encoding can be achived by using LabelEncoder

In [46]:
df['CAEC'].unique()

array(['Sometimes', 'Frequently', 'Always', 'no'], dtype=object)

In [47]:
df['CAEC'].dtype

dtype('O')

In [49]:
# Creating a instance of label Encoder.
le = LabelEncoder()
 
# Using .fit_transform function to fit label
# encoder and return encoded label
caec_encoded = le.fit_transform(df['CAEC'])
 
# printing label
set(caec_encoded)

{0, 1, 2, 3}

In [50]:
# Encoding the 'family_history_with_overweight' column
df['CAEC'] = caec_encoded

# Updated Dataframe 
df.head()

,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad,Gender_Female,Gender_Male
0,21.0,1.62,64.0,1,0,2.0,3.0,2,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,1.0,0.0
1,21.0,1.52,56.0,1,0,3.0,3.0,2,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,1.0,0.0
2,23.0,1.80,77.0,1,0,2.0,3.0,2,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,0.0,1.0
3,27.0,1.80,87.0,0,0,3.0,3.0,2,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,0.0,1.0
4,22.0,1.78,89.8,0,0,2.0,1.0,2,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,0.0,1.0

#### Feature 10:

**SMOKE**: Indicates whether the individual is a smoker or not (Yes or No).

- this feature contain binary values - yes or no.
- this can also be encoded using LabelEncoder function

In [51]:
df['SMOKE'].unique()

array(['no', 'yes'], dtype=object)

In [52]:
# Creating a instance of label Encoder.
le = LabelEncoder()
 
# Using .fit_transform function to fit label
# encoder and return encoded label
smoke_encoded = le.fit_transform(df['SMOKE'])
 
# printing label
smoke_encoded

array([0, 1, 0, ..., 0, 0, 0])

In [53]:
# Encoding the 'family_history_with_overweight' column
df['SMOKE'] = smoke_encoded

# Updated Dataframe 
df.head()

,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad,Gender_Female,Gender_Male
0,21.0,1.62,64.0,1,0,2.0,3.0,2,0,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,1.0,0.0
1,21.0,1.52,56.0,1,0,3.0,3.0,2,1,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,1.0,0.0
2,23.0,1.80,77.0,1,0,2.0,3.0,2,0,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,0.0,1.0
3,27.0,1.80,87.0,0,0,3.0,3.0,2,0,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,0.0,1.0
4,22.0,1.78,89.8,0,0,2.0,1.0,2,0,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,0.0,1.0

#### Feature 12:

**SCC**: Represents the calories consumption monitoring (Yes or No).

- this feature contain binary values - yes or no.
- this can also be encoded using LabelEncoder function

In [54]:
df['SCC'].unique()

array(['no', 'yes'], dtype=object)

In [55]:
# Creating a instance of label Encoder.
le = LabelEncoder()
 
# Using .fit_transform function to fit label
# encoder and return encoded label
scc_encoded = le.fit_transform(df['SCC'])
 
# printing label
scc_encoded

array([0, 1, 0, ..., 0, 0, 0])

In [56]:
# Encoding the 'family_history_with_overweight' column
df['SCC'] = scc_encoded

# Updated Dataframe 
df.head()

,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad,Gender_Female,Gender_Male
0,21.0,1.62,64.0,1,0,2.0,3.0,2,0,2.0,0,0.0,1.0,no,Public_Transportation,Normal_Weight,1.0,0.0
1,21.0,1.52,56.0,1,0,3.0,3.0,2,1,3.0,1,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,1.0,0.0
2,23.0,1.80,77.0,1,0,2.0,3.0,2,0,2.0,0,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,0.0,1.0
3,27.0,1.80,87.0,0,0,3.0,3.0,2,0,2.0,0,2.0,0.0,Frequently,Walking,Overweight_Level_I,0.0,1.0
4,22.0,1.78,89.8,0,0,2.0,1.0,2,0,2.0,0,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,0.0,1.0